In [3]:
import numpy as np
print(np.__version__)

1.16.5


In [8]:
print(np.arange(10))
type(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [7]:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
arr = np.arange(10)
arr[arr%2==1]


array([1, 3, 5, 7, 9])

In [12]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [17]:
arr = np.arange(10)
arr2 = np.where(arr%2==1,-1,arr)
print(arr)
arr2

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [22]:
arr = np.arange(10)
print(arr)
arr.reshape(2,5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(a)
print(b)

print(np.concatenate([a,b]))
print(np.vstack([a,b]))
print(np.r_[a,b])
type(np.concatenate([a,b]))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


numpy.ndarray

In [36]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(np.concatenate((a,b),axis=1))
print(np.hstack([a,b]))
print(np.c_[a,b])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [47]:
a = np.array([1,2,3])
a
#np.concatenate([np.repeat(a, 3), np.tile(a,3)])
np.r_[np.repeat(a, 3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [54]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [56]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [57]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,4,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [74]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
#method1
a[(a>4)*(a<11)] 
#method2
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#method3
index = np.where((5<=a) & (a<=10))
a[index]

array([ 6,  9, 10])

In [91]:
def maxx(x,y):
    if x>=y:
        return x
    else:
        return y
pair_max = np.vectorize(maxx, otypes=[int])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [93]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[[1,0,2],:])
print(arr[:,[1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [98]:
arr = np.arange(9).reshape(3,3)
#[a:b:c] --> start, stop, step
print(arr)
print(arr[:,::-1])
print(arr[::-1,::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[8 7 6]
 [5 4 3]
 [2 1 0]]


In [108]:
#method 1
a = np.random.uniform(low=5, high=10, size=(5,3))
a
#method 2
c = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
c

array([[9.6697775 , 9.40269845, 8.14640464],
       [9.61258053, 6.08843351, 6.63138563],
       [6.67328827, 6.85074689, 7.37405416],
       [8.85027322, 6.31499712, 5.26798111],
       [9.80520867, 6.32975952, 7.92345225]])

In [111]:
rand_arr = np.random.random((5,3)).round(decimals = 3)
rand_arr

array([[0.154, 0.175, 0.945],
       [0.609, 0.749, 0.795],
       [0.081, 0.612, 0.054],
       [0.998, 0.547, 0.316],
       [0.458, 0.482, 0.788]])

In [141]:
np.random.seed(100)
np.set_printoptions(precision=6, suppress=1)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [3]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
#method 1
a = np.loadtxt(r"C:\Users\nandkumar\Downloads\iris.data", delimiter=',', dtype = 'object')
print(a)
#method 2
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
b = np.genfromtxt(url, delimiter = ',', dtype = 'object')
b

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']
 ['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['5.1' '3.3' '1.7' '0.5' 'Iris-setosa']
 ['4.8' '3.4' '1

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

In [33]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
a = np.genfromtxt(url, delimiter=',',dtype=None)
print(a.shape)
a[:5]

(150,)


C:\Users\nandkumar\New folder\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, b'Iris-setosa')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

In [43]:
#method 1
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris2d = np.array(np.genfromtxt(url, delimiter=',', dtype=None, usecols=[0,1,2,3]))
#method 2
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [46]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=None, usecols=[0])
mean, median, sd = np.mean(iris), np.median(iris), np.std(iris)
print(mean, median, sd)

5.843333333333334 5.8 0.8253012917851409


In [5]:
#method  1
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
irismax, irismin = np.max(iris), np.min(iris)
iris_norm = (iris - irismin) / (irismax - irismin)
print(iris_norm)
#method 2
iris_norm2 = (iris - irismin) / iris.ptp()
print(iris_norm2)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

In [56]:
a = np.exp(iris)/sum(np.exp(iris))
print(a.round(decimals = 3))

[0.002 0.002 0.001 0.001 0.002 0.003 0.001 0.002 0.001 0.002 0.003 0.002
 0.002 0.001 0.004 0.004 0.003 0.002 0.004 0.002 0.003 0.002 0.001 0.002
 0.002 0.002 0.002 0.002 0.002 0.001 0.002 0.003 0.002 0.003 0.002 0.002
 0.003 0.002 0.001 0.002 0.002 0.001 0.001 0.002 0.002 0.002 0.002 0.001
 0.003 0.002 0.015 0.008 0.013 0.003 0.009 0.004 0.007 0.002 0.01  0.002
 0.002 0.005 0.005 0.006 0.004 0.011 0.004 0.004 0.007 0.004 0.005 0.006
 0.007 0.006 0.008 0.01  0.012 0.011 0.005 0.004 0.003 0.003 0.004 0.005
 0.003 0.005 0.011 0.007 0.004 0.003 0.003 0.006 0.004 0.002 0.004 0.004
 0.004 0.007 0.002 0.004 0.007 0.004 0.016 0.007 0.009 0.027 0.002 0.02
 0.011 0.018 0.009 0.008 0.012 0.004 0.004 0.008 0.009 0.03  0.03  0.005
 0.013 0.004 0.03  0.007 0.011 0.018 0.007 0.006 0.008 0.018 0.022 0.037
 0.008 0.007 0.006 0.03  0.007 0.008 0.005 0.013 0.011 0.013 0.004 0.012
 0.011 0.011 0.007 0.009 0.007 0.005]


In [6]:
print(np.percentile(iris, q=[5,95]))

[4.6   7.255]


In [18]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# method 1
index = np.random.choice(iris_2d.size, 20, replace=False)
iris_2d.ravel()[index] = np.nan
print(iris_2d)

# method 2
x,y = np.asarray(iris_2d).nonzero()
np.random.seed(100)
iris_2d[np.random.choice((x),20),np.random.choice((y),20)] = np.nan

# method 3
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' nan b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' nan b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' nan b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' nan b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Iris-setosa']


In [37]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(np.isnan(iris_2d[:,0]).sum())
print(np.where(np.isnan(iris_2d[:,0])))

7
(array([ 26,  31,  60,  68,  84, 108, 132], dtype=int64),)


In [38]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(np.where(iris_2d[3,:])>1.5)

TypeError: '>' not supported between instances of 'tuple' and 'float'